### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by gabidavila** [Litipk/Jupyter-PHP-Installer#19]
Hi,

I am using High Sierra and Jupyter Notebook. I successfully installed the PHP Kernel, however no Syntax Highlighting is appearing on it.

I also find it weird that my Jupyter Notebook to start is not `jupyter notebook` and it is `jupyter-notebook`. I installed it through `brew`.

Is anything I am missing? 🤔

**Comment by castarco** [comment]
Hi @gabidavila :) ,

1. **Syntax highlighting:** The problem is not related with the "PHP kernel" for Jupyter, but with the "Pygments"  library used by Jupyter Notebook. It seems that it only highlights the code when the `<?php`  piece of code is put at the beginning. My recommendation (if you need/want highlighting) is to write `// <?php` as the first line. The comment lines are required because the PHP kernel already assumes that is working with PHP, so finding the opening tag may cause problems.

2. Command line: Mmmm... I don't know. Three months have passed since the last day I touched Jupyter in my own computer, so I don't remember the exact commands that should be used.
